---
motives:
  8192:
    dose: 3
    vaccin: Pfizer-BioNTech

  8193:
    dose: 3
    vaccin: Moderna

  10515:
    dose: 1_kid
    vaccin: Pfizer-BioNTech

  10516:
    dose: 1_kid
    vaccin: Pfizer-BioNTech
